### ISSUE TITLE
Async query context fails with NRE if where were no subqueries registered

### ISSUE THREAD

**Issue by PeopleDispose** [PeopleDispose/CS-GO-Bets#51]
```
System.NullReferenceException

   at CsgoBets.Store.Repositories.AsyncQueryObjects.DbSetAsyncEntityContext`1.QueryModificationChain.Modify(IQueryable`1 sourceQuery) in D:\CS-GO-Bets\src\CsgoBets.Store\Repositories\AsyncQueryObjects\DbSetAsyncEntityContext.QueryModificationChain.cs:line 27
   at CsgoBets.Store.Repositories.AsyncQueryObjects.DbSetAsyncEntityContext`1.GetQueryable() in D:\CS-GO-Bets\src\CsgoBets.Store\Repositories\AsyncQueryObjects\DbSetAsyncEntityContext.cs:line 25
   at CsgoBets.Store.Repositories.AsyncQueryObjects.ModificationAsyncEntityContext`2.GetQueryable() in D:\CS-GO-Bets\src\CsgoBets.Store\Repositories\AsyncQueryObjects\ModificationAsyncEntityContext.cs:line 50
   at CsgoBets.Store.Repositories.AsyncQueryObjects.ModificationAsyncEntityContext`2.GetArrayAsync() in D:\CS-GO-Bets\src\CsgoBets.Store\Repositories\AsyncQueryObjects\ModificationAsyncEntityContext.cs:line 25
   at CsgoBets.Jobs.Status.JobExplorer.<GetAvailableJobsAsync>d__4.MoveNext() in D:\CS-GO-Bets\src\CsgoBets.Jobs\Status\JobExplorer.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CsgoBets.ClientWeb.API.Controllers.JobController.<GetAsync>d__0.MoveNext() in D:\CS-GO-Bets\src\CsgoBets.ClientWeb.API\Controllers\JobController.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

**Comment by PeopleDispose** [comment]
fixed in https://github.com/PeopleDispose/CS-GO-Bets/pull/52
